[package]
name = "rocket_okapi_codegen"
description = "Macros supporting rocket_okapi"
repository = "https://github.com/GREsau/okapi"
version = "0.6.0-alpha-1"
authors = ["Graham Esau <gesau@hotmail.co.uk>"]
edition = "2018"
license = "MIT"
keywords = ["rust", "openapi", "swagger", "rocket"]

[lib]
proc-macro = true

[dependencies]
rocket_http = { git ="https://github.com/SergioBenitez/Rocket", version = "0.5.0-dev" }
darling = "0.10"
syn = "1.0"
proc-macro2 = "1.0"
quote = "1.0"
